import { baseLuckyWheelAbi } from "@/lib/abi/baseLuckyWheelAbi";

export const BASELUCKYWHEEL_CONTRACT_ADDRESS_PLACEHOLDER =
  "BASELUCKYWHEEL_CONTRACT_ADDRESS_PLACEHOLDER";
export const BASE_APP_ID_PLACEHOLDER = "BASE_APP_ID_PLACEHOLDER";
export const TALENT_VERIFICATION_PLACEHOLDER = "TALENT_VERIFICATION_PLACEHOLDER";
export const BUILDER_CODE_PLACEHOLDER = "BUILDER_CODE_PLACEHOLDER";
export const GITHUB_TOKEN_PLACEHOLDER = "GITHUB_TOKEN_PLACEHOLDER";
export const VERCEL_TOKEN_PLACEHOLDER = "VERCEL_TOKEN_PLACEHOLDER";

export const BASELUCKYWHEEL_CONTRACT_ADDRESS =
  "0x8E40cF11E39F8E35Eb83EdC4dB2f962ec3BD7416" as const;
export const PLAY_FEE_WEI = 1000000000000n;
export const PLAY_FEE_LABEL = "0.000001 ETH";
export const APP_ID = "app-009";
export const APP_NAME = "BaseLuckyWheel";

export const luckyWheelContract = {
  address: BASELUCKYWHEEL_CONTRACT_ADDRESS,
  abi: baseLuckyWheelAbi
} as const;
